#!/bin/bash
originalPath=$(awk /$filename/'{print $4}' "$HOME/trash/.log")

filenameNow=$(awk /$filename/'{print $1}' "$HOME/trash/.log")
filenamebefore=$(awk /$filename/'{print $2}' "$HOME/trash/.log")
echo "you are about to restore $filenameNow,original name is $filenamebefore"
echo "original path is $originalPath"

echo "Are you sure to do that?[Y/N]"
    read reply
    if [ $reply = "y" ] || [ $reply = "Y" ]
     then 
$(mv -b "$HOME/trash/$filenameNow" $originalPath)
$(sed -i /$filenameNow/'d' "$HOME/trash/.log")
    else
        echo "no files restored"
    fi